### ISSUE TITLE
public value is always true

### ISSUE THREAD

**Issue by PodyNoo** [paulgreg/rsstodolist-node-server#27]
I'm using a docker compose with environment variable `PUBLIC=false`

public value is always true when used as a boolean, for example here :
https://github.com/paulgreg/rsstodolist-node-server/blob/0dcbb13318a1af3d59c1c2c63183166f694123e3/src/views/rss.ejs#L10

Because it's interpreted as a string and not a boolean here :
https://github.com/paulgreg/rsstodolist-node-server/blob/0dcbb13318a1af3d59c1c2c63183166f694123e3/src/env.mjs#L13

Maybe something like this would fix the problem : `export const PUBLIC = process.env.PUBLIC === "true"`

Thanks a lot for your project, it's really useful !

**Comment by paulgreg** [comment]
You’re right.
I’ve usually didn’t set `PUBLIC` environment variable but your proposition is better.
I’ve fixed that.

I’ve also updated dependencies. It has been a while.

Thanks
